version: "3.8"

services:
  web:
    build: .
    environment:
      MODEL_PATH: models/blue/model.pkl
      MODEL_FEATURES_PATH: models/blue/model_features.json
      DEMOGRAPHICS_PATH: data/zipcode_demographics.csv
      MODEL_VERSION: "1.0"
    volumes:
      - ./models/model:/app/blue/model:ro
      - ./data/zipcode_demographics.csv:/app/data/zipcode_demographics.csv:ro
    expose:
      - "8000"
    restart: on-failure
    command: gunicorn Project_phData.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 60

  web_green:
    build: .
    environment:
      MODEL_PATH: models/green/model.pkl
      MODEL_FEATURES_PATH: models/green/model_features.json
      DEMOGRAPHICS_PATH: data/zipcode_demographics.csv
      MODEL_VERSION: "2.0"
    volumes:
      - ./models/model_V2:/app/models/green:ro
      - ./data/zipcode_demographics.csv:/app/data/zipcode_demographics.csv:ro
    expose:
      - "8000"
    restart: on-failure
    command: gunicorn Project_phData.wsgi:application --bind 0.0.0.0:8000 --workers 3 --timeout 60

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
      - web_green